"""Generate the pre-writing revision tables and Figures 1--4, 7, and 8.

Figures 5 and 6 are generated by their dedicated frozen scripts.  This module
uses only frozen design files and completed Gate 1--4 results.  It deliberately
keeps panel letters out of artwork so LaTeX can supply subfigure labels.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.patheffects as pe
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap, LogNorm, TwoSlopeNorm
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Polygon, Rectangle
import numpy as np
import pandas as pd
from pyproj import Transformer


ROOT = Path(__file__).resolve().parent.parent
PW = ROOT / "production_workflow"
DESIGN = PW / "frozen_design"
GATE1 = PW / "gate1_results/gate1_lcurve_selection_bundle_20260819_a/evidence/diag_regc_0p014142_confirm01_r2"
DATASET = PW / "gate2_results/gate2_canonical_dataset_20260820_c"
SUPPORT = PW / "gate2_results/gate2_distribution_diagnostics_20260820_c"
PREDICTIONS = PW / "gate3_full_mesh_ensemble_predictions_20260828_a"
FORWARD = PW / "gate4_forward_evaluation_20260829_a"
REPORTING = PW / "gate4_forward_reporting_20260829_b"
C_DIAG = PW / "gate4_c_diagnostics_20260829_a"
FOOTPRINT_ERRORS = PW / "gate4_square_footprint_error_maps_20260830_b"
OUT = PW / "final_figures_20260830_a"
ANTARCTICA_LAND = DESIGN / "ne_110m_land.geojson"
DOMAIN_OUTLINE = ROOT / "tmp/amundsen_v1.geojson"

CONFIGS = [f"CFG{i:02d}" for i in range(1, 7)]
CONFIG_LABELS = {
    "CFG01": "All ice",
    "CFG02": "Selected ice",
    "CFG03": "All geophysical",
    "CFG04": "Selected geophysical",
    "CFG05": "Selected combined",
    "CFG06": "Combined + alignment",
}
CONFIG_COLORS = {
    "CFG01": "#4477AA",
    "CFG02": "#66CCEE",
    "CFG03": "#228833",
    "CFG04": "#CCBB44",
    "CFG05": "#EE6677",
    "CFG06": "#AA3377",
}
FEATURES = {
    "s": ("Surface elevation", "m", "BedMachine Antarctica"),
    "h": ("Ice thickness", "m", "BedMachine Antarctica"),
    "mag_s": ("Surface-gradient magnitude", "dimensionless", "Derived from surface elevation"),
    "mag_h": ("Thickness-gradient magnitude", "dimensionless", "Derived from ice thickness"),
    "driving_stress": ("Driving stress", "MPa", "Derived from geometry; Icepack-native stress unit"),
    "surface_air_temp": ("Surface air temperature", "deg C", "Quantarctica raster"),
    "b": ("Bed elevation", "m", "BedMachine Antarctica"),
    "mag_b": ("Bed-gradient magnitude", "dimensionless", "Derived from bed elevation"),
    "heatflux": ("Geothermal heat flux", "mW m-2", "Quantarctica raster"),
    "gravity_disturbance": ("Gravity disturbance", "mGal", "AntGG2021"),
    "mag_anomaly": ("Magnetic anomaly", "nT", "ADMAP2S"),
    "cos_theta_bs": ("Bed--surface gradient alignment", "dimensionless", "Derived; cosine similarity"),
}
CONFIG_FEATURES = {
    "CFG01": ["s", "h", "mag_s", "mag_h", "driving_stress", "surface_air_temp"],
    "CFG02": ["s", "h", "mag_s", "mag_h", "surface_air_temp"],
    "CFG03": ["b", "mag_b", "heatflux", "gravity_disturbance", "mag_anomaly"],
    "CFG04": ["b", "mag_b", "heatflux"],
    "CFG05": ["s", "h", "mag_s", "mag_h", "surface_air_temp", "b", "mag_b", "heatflux"],
    "CFG06": ["s", "h", "mag_s", "mag_h", "surface_air_temp", "b", "mag_b", "heatflux", "cos_theta_bs"],
}


def style() -> None:
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 9.0,
        "axes.titlesize": 10.5, "axes.labelsize": 10.5,
        "xtick.labelsize": 9.0, "ytick.labelsize": 9.0,
        "legend.fontsize": 9.0, "axes.linewidth": 0.8,
        "pdf.fonttype": 42, "svg.fonttype": "none",
        "savefig.dpi": 300,
    })


def save(fig: plt.Figure, stem: str) -> list[Path]:
    paths = []
    for suffix in ("png", "pdf", "svg"):
        path = OUT / f"{stem}.{suffix}"
        fig.savefig(path, bbox_inches="tight", pad_inches=0.05)
        paths.append(path)
    plt.close(fig)
    return paths


def sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def grid_context() -> dict[str, np.ndarray]:
    with np.load(DESIGN / "amundsen_input_support_grid_5km.npz", allow_pickle=False) as z:
        return {k: z[k] for k in z.files}


def region_context() -> dict[str, np.ndarray]:
    with np.load(DESIGN / "five_region_partition_5km.npz", allow_pickle=False) as z:
        return {k: z[k] for k in z.files}


def square_table() -> pd.DataFrame:
    return pd.read_csv(DESIGN / "selected_squares.csv")


def aggregate_velocity_grid() -> dict[str, np.ndarray]:
    cache = OUT / "revision_velocity_grid_5km.npz"
    if cache.exists():
        with np.load(cache, allow_pickle=False) as z:
            return {k: z[k] for k in z.files}
    g = grid_context()
    xg, yg = g["x_grid"], g["y_grid"]
    sums = {k: np.zeros((len(yg), len(xg)), dtype=float) for k in ("speed", "error")}
    count = np.zeros((len(yg), len(xg)), dtype=np.int64)
    columns = ["x", "y", "observed_speed", "observed_vx", "observed_vy", "inversion_vx", "inversion_vy"]
    source = DATASET / "canonical_master_dataset.csv.gz"
    for chunk in pd.read_csv(source, usecols=columns, chunksize=200_000):
        ix = np.rint((chunk["x"].to_numpy() - xg[0]) / 5000).astype(int)
        iy = np.rint((chunk["y"].to_numpy() - yg[0]) / 5000).astype(int)
        valid = (ix >= 0) & (ix < len(xg)) & (iy >= 0) & (iy < len(yg))
        speed = chunk["observed_speed"].to_numpy()
        err = np.hypot(chunk["inversion_vx"] - chunk["observed_vx"],
                       chunk["inversion_vy"] - chunk["observed_vy"]).to_numpy()
        valid &= np.isfinite(speed) & np.isfinite(err)
        np.add.at(sums["speed"], (iy[valid], ix[valid]), speed[valid])
        np.add.at(sums["error"], (iy[valid], ix[valid]), err[valid])
        np.add.at(count, (iy[valid], ix[valid]), 1)
    result = {"x_grid": xg, "y_grid": yg, "count": count}
    for key, values in sums.items():
        result[key] = np.divide(values, count, out=np.full_like(values, np.nan), where=count > 0)
    np.savez_compressed(cache, **result)
    return result


def domain_outline() -> dict:
    return json.loads(DOMAIN_OUTLINE.read_text(encoding="utf-8"))


def map_axes(ax: plt.Axes, outline: np.ndarray) -> None:
    # Use the complete model-domain linework, including the open-ocean ice-front
    # (terminus) segments.  The legacy flattened outline omitted those segments.
    for feature in domain_outline()["features"]:
        geometry = feature["geometry"]
        lines = geometry["coordinates"] if geometry["type"] == "MultiLineString" else [geometry["coordinates"]]
        for line in lines:
            points = np.asarray(line, dtype=float) / 1000.0
            ax.plot(points[:, 0], points[:, 1], color="0.08", lw=0.85, zorder=8)
    ax.set_aspect("equal")
    ax.set_xlabel("Polar stereographic x (km)")
    ax.set_ylabel("Polar stereographic y (km)")
    ax.tick_params(direction="out", length=2.5)


def antarctica_rings() -> list[np.ndarray]:
    payload = json.loads(ANTARCTICA_LAND.read_text(encoding="utf-8"))
    transformer = Transformer.from_crs("EPSG:4326", "EPSG:3031", always_xy=True)
    rings: list[np.ndarray] = []
    for feature in payload["features"]:
        geometry = feature["geometry"]
        polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
        for polygon in polygons:
            if not polygon:
                continue
            ring = np.asarray(polygon[0], dtype=float)
            if ring.ndim != 2 or ring.shape[1] != 2 or np.nanmin(ring[:, 1]) > -60:
                continue
            xx, yy = transformer.transform(ring[:, 0], ring[:, 1])
            rings.append(np.column_stack([xx, yy]) / 1000.0)
    if not rings:
        raise RuntimeError("Natural Earth input contains no Antarctic land rings")
    return rings


def add_antarctica_locator(ax: plt.Axes, outline: np.ndarray) -> None:
    inset = ax.inset_axes([0.765, 0.755, 0.21, 0.21])
    for ring in antarctica_rings():
        inset.add_patch(Polygon(ring, closed=True, facecolor="0.78", edgecolor="0.25", lw=0.35))
    xmin, ymin = np.min(outline, axis=0) / 1000.0
    xmax, ymax = np.max(outline, axis=0) / 1000.0
    inset.add_patch(Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, fill=False, edgecolor="#8B0015", lw=1.1))
    inset.set_xlim(-2900, 2900); inset.set_ylim(-2600, 2600)
    inset.set_aspect("equal"); inset.set_xticks([]); inset.set_yticks([])
    inset.set_facecolor("#DDEEF4")
    for spine in inset.spines.values():
        spine.set_linewidth(.45); spine.set_color("0.35")


def draw_speed_basemap(ax: plt.Axes, r: dict[str, np.ndarray], v: dict[str, np.ndarray], alpha: float = .24) -> None:
    x, y = r["x_grid"] / 1000.0, r["y_grid"] / 1000.0
    extent = [x[0] - 2.5, x[-1] + 2.5, y[0] - 2.5, y[-1] + 2.5]
    speed = np.ma.masked_where(~r["eligible"] | ~np.isfinite(v["speed"]), v["speed"])
    ax.imshow(speed, origin="lower", extent=extent, cmap="Greys",
              norm=LogNorm(vmin=max(1, np.nanpercentile(speed.compressed(), 1)),
                           vmax=np.nanpercentile(speed.compressed(), 99.5)),
              alpha=alpha, zorder=0)


def figure1() -> list[Path]:
    r, g, v, sq = region_context(), grid_context(), aggregate_velocity_grid(), square_table()
    x, y = r["x_grid"] / 1000, r["y_grid"] / 1000
    extent = [x[0] - 2.5, x[-1] + 2.5, y[0] - 2.5, y[-1] + 2.5]
    speed = np.ma.masked_where(~r["eligible"] | ~np.isfinite(v["speed"]), v["speed"])
    labels = {1: "Pine Island", 2: "Thwaites", 3: "Dotson",
              4: "PIG--Thwaites\ncorridor", 5: "Thwaites--Dotson\ncorridor"}
    base = np.ma.masked_where(~r["eligible"], r["region_codes"])
    cmap = ListedColormap(["#6baed6", "#9ecae1", "#74c476", "#fdae6b", "#fdd0a2"])

    def draw_region_panel(fig: plt.Figure, ax: plt.Axes, show_title: bool) -> None:
        im = ax.imshow(speed, origin="lower", extent=extent, cmap="viridis",
                       norm=LogNorm(vmin=max(1, np.nanpercentile(speed.compressed(), 1)),
                                    vmax=np.nanpercentile(speed.compressed(), 99.5)))
        ax.contour(x, y, r["region_codes"], levels=[1.5, 2.5, 3.5, 4.5], colors="white", linewidths=0.7)
        for code, label in labels.items():
            yy, xx = np.where(r["region_codes"] == code)
            if len(xx):
                ax.text(np.median(x[xx]), np.median(y[yy]), label, color="white",
                        ha="center", va="center", fontsize=8.7, fontweight="bold",
                        path_effects=[pe.Stroke(linewidth=1.8, foreground="0.15"), pe.Normal()],
                        zorder=9)
        map_axes(ax, r["outline"])
        add_antarctica_locator(ax, r["outline"])
        if show_title:
            ax.set_title("Observed surface speed and frozen regional partition")
        cb = fig.colorbar(im, ax=ax, shrink=1.0, pad=0.02)
        cb.set_label("Observed speed (m a$^{-1}$)")

    def draw_holdout_panel(ax: plt.Axes, show_title: bool) -> None:
        ax.imshow(base, origin="lower", extent=extent, cmap=cmap,
                  norm=BoundaryNorm(np.arange(0.5, 6.5), 5), alpha=0.55)
        for row in sq.itertuples():
            fx = row.footprint_xmin_m / 1000; fy = row.footprint_ymin_m / 1000
            tx = row.test_xmin_m / 1000; ty = row.test_ymin_m / 1000
            ax.add_patch(Rectangle((fx, fy), 130, 130, fill=False, edgecolor="0.35", lw=0.55, ls="--"))
            ax.add_patch(Rectangle((tx, ty), 50, 50, facecolor="none", edgecolor="#7A0019", lw=1.2))
            ax.text(row.center_x_m / 1000, row.center_y_m / 1000, row.square_id.replace("SQ", ""),
                    ha="center", va="center", color="#7A0019", fontsize=7.2, fontweight="bold")
        map_axes(ax, r["outline"])
        add_antarctica_locator(ax, r["outline"])
        if show_title:
            ax.set_title("Ten held-out 50 km squares and 130 km exclusion footprints")
        ax.plot([], [], color="#7A0019", lw=1.2, label="Evaluation square")
        ax.plot([], [], color="0.35", lw=0.55, ls="--", label="Training-exclusion footprint")
        ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.10), ncol=2,
                  frameon=True, framealpha=0.95, borderaxespad=0.0)

    paths: list[Path] = []
    fig, axes = plt.subplots(1, 2, figsize=(11.4, 5.2), constrained_layout=True)
    draw_region_panel(fig, axes[0], True)
    draw_holdout_panel(axes[1], True)
    paths.extend(save(fig, "figure1_study_region_and_holdouts"))

    fig_a, ax_a = plt.subplots(figsize=(5.9, 5.2), constrained_layout=True)
    draw_region_panel(fig_a, ax_a, False)
    paths.extend(save(fig_a, "figure1a_observed_speed_and_regions"))
    fig_b, ax_b = plt.subplots(figsize=(5.6, 5.2), constrained_layout=True)
    draw_holdout_panel(ax_b, False)
    paths.extend(save(fig_b, "figure1b_holdout_geometry"))
    return paths


def figure2() -> list[Path]:
    fig, ax = plt.subplots(figsize=(11.2, 4.6))
    ax.set_xlim(0, 1.04); ax.set_ylim(0, 1); ax.axis("off")
    lanes = [
        (0.80, "Icepack / CPU", [
            (0.12, "Geophysical\nrasters + velocity"), (0.34, "Whole-sector\ninversion"),
            (0.56, "Canonical mesh\ndataset"), (0.78, "ML-augmented\nforward solves")]),
        (0.46, "CUDA training", [
            (0.34, "Frozen row-ID\nsplits"), (0.56, "660 reproducible\nMLP fits"), (0.78, "66 median\nensembles")]),
        (0.12, "Evaluation", [
            (0.34, "Input-support\ndiagnostics"), (0.56, "$C$ diagnostics\n(secondary)"),
            (0.78, "Velocity skill\n(primary test)")]),
    ]
    colors = ["#E8F1FA", "#F0EAF6", "#EAF4EA"]
    boxes = {}
    for lane_idx, (yy, label, items) in enumerate(lanes):
        ax.text(0.01, yy, label, ha="left", va="center", fontweight="bold", fontsize=9)
        for x0, text in items:
            box = FancyBboxPatch((x0, yy - 0.085), 0.17, 0.17,
                                 boxstyle="round,pad=0.012,rounding_size=0.012",
                                 facecolor=colors[lane_idx], edgecolor="0.35", lw=0.8)
            ax.add_patch(box); ax.text(x0 + 0.085, yy, text, ha="center", va="center", fontsize=8)
            boxes[(lane_idx, x0)] = (x0, x0 + 0.17, yy)
    def arrow(a, b, color="0.25", style="-"):
        ax.add_patch(FancyArrowPatch(a, b, arrowstyle="-|>", mutation_scale=11, lw=1.0,
                                     color=color, linestyle=style, connectionstyle="arc3,rad=0"))
    arrow((.29, .80), (.34, .80)); arrow((.51, .80), (.56, .80)); arrow((.73, .80), (.78, .80))
    arrow((.51, .46), (.56, .46)); arrow((.73, .46), (.78, .46))
    arrow((.51, .12), (.56, .12)); arrow((.73, .12), (.78, .12))
    arrow((.645, .715), (.645, .555)); arrow((.865, .555), (.865, .715)); arrow((.645, .375), (.645, .215))
    arrow((1.025, .12), (.955, .12), color="#7A0019")
    ax.text(.99, .155, "observations", ha="center", va="bottom", fontsize=7, color="#7A0019")
    ax.text(.50, .965, "Data construction, training, and outcome-blind held-out evaluation", ha="center", va="top", fontsize=11)
    return save(fig, "figure2_end_to_end_workflow")


def figure3() -> list[Path]:
    r, v = region_context(), aggregate_velocity_grid()
    coords = np.load(GATE1 / "state_coordinates.npy") / 1000
    cfield = np.load(GATE1 / "state_C.npy")
    x, y = r["x_grid"] / 1000, r["y_grid"] / 1000
    extent = [x[0] - 2.5, x[-1] + 2.5, y[0] - 2.5, y[-1] + 2.5]
    speed = np.ma.masked_where(~r["eligible"] | ~np.isfinite(v["speed"]), v["speed"])
    finite_c = cfield[np.isfinite(cfield)]
    err = np.ma.masked_where(~r["eligible"] | ~np.isfinite(v["error"]), v["error"])

    def finish_map(ax: plt.Axes) -> None:
        map_axes(ax, r["outline"])
        add_antarctica_locator(ax, r["outline"])

    def draw_speed(fig: plt.Figure, ax: plt.Axes, show_title: bool) -> None:
        im = ax.imshow(speed, origin="lower", extent=extent, cmap="viridis",
                       norm=LogNorm(vmin=max(1, np.nanpercentile(speed.compressed(), 1)),
                                    vmax=np.nanpercentile(speed.compressed(), 99.5)))
        if show_title:
            ax.set_title("Observed surface speed")
        cb = fig.colorbar(im, ax=ax, shrink=.88, pad=.02); cb.set_label("m a$^{-1}$")
        finish_map(ax)

    def draw_c(fig: plt.Figure, ax: plt.Axes, show_title: bool) -> None:
        im = ax.scatter(coords[:, 0], coords[:, 1], c=cfield, s=1.4, cmap="magma",
                        vmin=np.quantile(finite_c, .01), vmax=np.quantile(finite_c, .99),
                        rasterized=True, linewidths=0)
        if show_title:
            ax.set_title("Inversion reference $C$")
        cb = fig.colorbar(im, ax=ax, shrink=.88, pad=.02); cb.set_label("Icepack $C$")
        finish_map(ax)

    def draw_error(fig: plt.Figure, ax: plt.Axes, show_title: bool) -> None:
        im = ax.imshow(err, origin="lower", extent=extent, cmap="inferno",
                       norm=LogNorm(vmin=max(.5, np.nanpercentile(err.compressed(), .1)),
                                    vmax=np.nanmax(err.compressed())))
        if show_title:
            ax.set_title("Inversion velocity residual")
        cb = fig.colorbar(im, ax=ax, shrink=.88, pad=.02)
        cb.set_label("Vector error (m a$^{-1}$; log scale)")
        finish_map(ax)

    paths: list[Path] = []
    fig, axes = plt.subplots(1, 3, figsize=(12.0, 4.3), constrained_layout=True)
    draw_speed(fig, axes[0], True); draw_c(fig, axes[1], True); draw_error(fig, axes[2], True)
    paths.extend(save(fig, "figure3_definitive_inversion"))
    for stem, drawer in (
        ("figure3a_observed_speed", draw_speed),
        ("figure3b_inversion_reference_c", draw_c),
        ("figure3c_inversion_velocity_residual", draw_error),
    ):
        panel, axis = plt.subplots(figsize=(4.6, 4.45), constrained_layout=True)
        drawer(panel, axis, False)
        paths.extend(save(panel, stem))
    return paths


def support_rows() -> pd.DataFrame:
    df = pd.read_csv(SUPPORT / "support_categories.csv")
    df["configuration"] = df["configuration"].str.slice(0, 5)
    return df.loc[df["experiment"].str.fullmatch(r"SQ\d{2}") & df["population"].eq("central_50km")].copy()


def figure4() -> list[Path]:
    df = support_rows()
    perf = pd.read_csv(FORWARD / "control_population_metrics.csv")
    perf = perf.loc[(perf["control_kind"] == "median") & perf["experiment"].str.fullmatch(r"SQ\d{2}")
                    & (perf["population"] == "central_50km") & (perf["support_stratum"] == "all")].copy()
    perf["relative_rmse_uniform"] = perf["vector_rmse_m_per_a"] / perf["uniform_vector_rmse_m_per_a"]
    df = df.merge(perf[["experiment", "configuration", "relative_rmse_uniform"]],
                  on=["experiment", "configuration"], validate="one_to_one")
    squares = [f"SQ{i:02d}" for i in range(1, 11)]
    support_matrix = df.pivot(index="experiment", columns="configuration", values="both_fraction").reindex(index=squares, columns=CONFIGS)
    ratio_matrix = df.pivot(index="experiment", columns="configuration", values="relative_rmse_uniform").reindex(index=squares, columns=CONFIGS)
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 4.9), constrained_layout=True)
    im0 = axes[0].imshow(100 * support_matrix.to_numpy(), aspect="auto", cmap="viridis", vmin=80, vmax=100)
    axes[0].set_title("Simultaneous marginal and joint support")
    for i in range(10):
        for j in range(6):
            value = 100 * support_matrix.iloc[i, j]
            axes[0].text(j, i, f"{value:.0f}", ha="center", va="center", fontsize=6.7,
                         color="white" if value < 95 else "black")
            if value < 95:
                axes[0].add_patch(Rectangle((j-.5, i-.5), 1, 1, fill=False, edgecolor="#C51B7D", lw=1.25))
    cb0 = fig.colorbar(im0, ax=axes[0], shrink=.78, pad=.02); cb0.set_label("Held-out area (%)")

    norm = TwoSlopeNorm(vcenter=1.0, vmin=0.2, vmax=2.4)
    im1 = axes[1].imshow(ratio_matrix.to_numpy(), aspect="auto", cmap="RdBu_r", norm=norm)
    axes[1].set_title("Velocity RMSE relative to uniform $C$")
    for i in range(10):
        for j in range(6):
            value = ratio_matrix.iloc[i, j]
            axes[1].text(j, i, f"{value:.2f}", ha="center", va="center", fontsize=6.5,
                         color="white" if value < .42 or value > 1.65 else "black")
            if value >= 1:
                axes[1].add_patch(Rectangle((j-.5, i-.5), 1, 1, fill=False, edgecolor="#C51B7D", lw=1.25))
    cb1 = fig.colorbar(im1, ax=axes[1], shrink=.78, pad=.02)
    cb1.set_label(r"RMSE$_{ML}$ / RMSE$_{uniform\ C}$")
    cb1.ax.axhline(1.0, color="black", lw=.7)
    for ax in axes:
        ax.set_xticks(range(6), CONFIGS, rotation=45, ha="right")
        ax.set_yticks(range(10), squares)
    axes[0].set_ylabel("Independent held-out square")
    axes[1].set_yticklabels([])
    paths = save(fig, "figure4_input_support")

    support_fig, support_ax = plt.subplots(figsize=(4.7, 5.0), constrained_layout=True)
    support_im = support_ax.imshow(100 * support_matrix.to_numpy(), aspect="auto", cmap="viridis", vmin=80, vmax=100)
    for i in range(10):
        for j in range(6):
            value = 100 * support_matrix.iloc[i, j]
            support_ax.text(j, i, f"{value:.0f}", ha="center", va="center", fontsize=7.2,
                            color="white" if value < 95 else "black")
            if value < 95:
                support_ax.add_patch(Rectangle((j-.5, i-.5), 1, 1, fill=False,
                                               edgecolor="#C51B7D", lw=1.25))
    support_ax.set_xticks(range(6), CONFIGS, rotation=45, ha="right")
    support_ax.set_yticks(range(10), squares)
    support_ax.set_ylabel("Independent held-out square")
    support_cb = support_fig.colorbar(support_im, ax=support_ax, shrink=.9, pad=.02)
    support_cb.set_label("Held-out area (%)")
    paths.extend(save(support_fig, "figure4a_input_support"))

    skill_fig, skill_ax = plt.subplots(figsize=(4.7, 5.0), constrained_layout=True)
    skill_im = skill_ax.imshow(ratio_matrix.to_numpy(), aspect="auto", cmap="RdBu_r", norm=norm)
    for i in range(10):
        for j in range(6):
            value = ratio_matrix.iloc[i, j]
            skill_ax.text(j, i, f"{value:.2f}", ha="center", va="center", fontsize=7.0,
                          color="white" if value < .42 or value > 1.65 else "black")
            if value >= 1:
                skill_ax.add_patch(Rectangle((j-.5, i-.5), 1, 1, fill=False,
                                             edgecolor="#C51B7D", lw=1.25))
    skill_ax.set_xticks(range(6), CONFIGS, rotation=45, ha="right")
    skill_ax.set_yticks(range(10), squares)
    skill_ax.set_ylabel("Independent held-out square")
    skill_cb = skill_fig.colorbar(skill_im, ax=skill_ax, shrink=.9, pad=.02)
    skill_cb.set_label(r"RMSE$_{ML}$ / RMSE$_{uniform\ C}$")
    skill_cb.ax.axhline(1.0, color="black", lw=.7)
    paths.extend(save(skill_fig, "figure4b_relative_velocity_skill"))
    return paths


def generate_tables() -> list[Path]:
    outputs = []
    predictor_rows = []
    for feature, (name, unit, source) in FEATURES.items():
        predictor_rows.append({"predictor": feature, "description": name, "unit": unit, "source_or_derivation": source,
                               **{cfg: "yes" if feature in CONFIG_FEATURES[cfg] else "" for cfg in CONFIGS}})
    t1 = pd.DataFrame(predictor_rows)
    p = OUT / "table1_predictors_and_configurations.csv"; t1.to_csv(p, index=False); outputs.append(p)

    summary = pd.read_csv(REPORTING / "square_equal_weight_summary.csv").drop(columns=["P_exp_median_percent"])
    perf = pd.read_csv(FORWARD / "control_population_metrics.csv")
    perf = perf.loc[(perf["control_kind"] == "median") & perf["experiment"].str.fullmatch(r"SQ\d{2}")
                    & (perf["population"] == "central_50km") & (perf["support_stratum"] == "all")].copy()
    perf["relative_rmse_uniform"] = perf["vector_rmse_m_per_a"] / perf["uniform_vector_rmse_m_per_a"]
    ratio_summary = perf.groupby("configuration")["relative_rmse_uniform"].agg(
        median_relative_RMSE_to_uniform="median",
        q25_relative_RMSE_to_uniform=lambda x: x.quantile(.25),
        q75_relative_RMSE_to_uniform=lambda x: x.quantile(.75),
    ).reset_index()
    summary = summary.merge(ratio_summary, on="configuration", validate="one_to_one")
    summary.insert(1, "configuration_label", summary["configuration"].map(CONFIG_LABELS))
    summary = summary.rename(columns={
        "vector_RMSE_median_m_per_a": "median_vector_RMSE_m_per_a",
        "vector_RMSE_q25_m_per_a": "q25_vector_RMSE_m_per_a",
        "vector_RMSE_q75_m_per_a": "q75_vector_RMSE_m_per_a",
    })
    p = OUT / "table2_primary_performance.csv"; summary.to_csv(p, index=False); outputs.append(p)

    support = support_rows()
    merged = support.merge(perf[["experiment", "configuration", "vector_rmse_m_per_a", "uniform_vector_rmse_m_per_a",
                                 "relative_rmse_uniform"]],
                           on=["experiment", "configuration"], validate="one_to_one")
    failures = merged.loc[(merged["both_fraction"] >= .95) & (merged["relative_rmse_uniform"] >= 1)].copy()
    failures = failures.sort_values(["experiment", "relative_rmse_uniform"], ascending=[True, False]).groupby("experiment", as_index=False).head(1)
    failures = failures[["experiment", "configuration", "minimum_marginal_coverage", "joint_coverage", "both_fraction",
                         "vector_rmse_m_per_a", "uniform_vector_rmse_m_per_a", "relative_rmse_uniform"]]
    failures.insert(2, "configuration_label", failures["configuration"].map(CONFIG_LABELS))
    p = OUT / "table3_high_support_low_skill_examples.csv"; failures.to_csv(p, index=False); outputs.append(p)
    full = merged.loc[(merged["both_fraction"] >= .95) & (merged["relative_rmse_uniform"] >= 1)].copy()
    p = OUT / "appendix_table_high_support_low_skill_all_cases.csv"; full.to_csv(p, index=False); outputs.append(p)

    # Compact LaTeX snippets; captions remain in the manuscript source.
    for frame, name in [(t1, "table1_predictors_and_configurations.tex"),
                        (summary, "table2_primary_performance.tex"),
                        (failures, "table3_high_support_low_skill_examples.tex")]:
        p = OUT / name
        def tex(value: object) -> str:
            if isinstance(value, (float, np.floating)):
                value = f"{value:.3f}"
            return str(value).replace("_", r"\_").replace("%", r"\%")
        lines = [r"\begin{tabular}{" + "l" * len(frame.columns) + "}",
                 " & ".join(tex(c) for c in frame.columns) + r" \\", r"\hline"]
        lines.extend(" & ".join(tex(v) for v in row) + r" \\" for row in frame.itertuples(index=False, name=None))
        lines.append(r"\end{tabular}")
        p.write_text("\n".join(lines) + "\n", encoding="utf-8")
        outputs.append(p)
    return outputs


def load_c_fields(config: str) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:
    squares = square_table()
    coords = reference = eligible = None
    predicted = np.full(1, np.nan)
    pieces = []
    for row in squares.itertuples():
        with np.load(PREDICTIONS / f"{row.square_id}_{config}.npz", allow_pickle=False) as z:
            c = z["coordinates"].astype(float); e = z["eligible_mask"].astype(bool)
            ref = z["reference_log_C"].astype(float); pred = z["median_log_C"].astype(float)
        if coords is None:
            coords, eligible, reference = c, e, ref
            predicted = np.full_like(ref, np.nan)
        elif not (np.array_equal(coords, c) and np.array_equal(eligible, e) and np.array_equal(reference, ref)):
            raise RuntimeError("Full-mesh prediction identity mismatch")
        mask = e & (c[:, 0] >= row.test_xmin_m) & (c[:, 0] <= row.test_xmax_m) \
                 & (c[:, 1] >= row.test_ymin_m) & (c[:, 1] <= row.test_ymax_m)
        predicted[mask] = pred[mask]
        pieces.append(pd.DataFrame({"square": row.square_id, "mask_index": np.flatnonzero(mask)}))
    mask = np.isfinite(predicted) & eligible
    return coords[mask] / 1000, reference[mask], predicted[mask], predicted[mask] - reference[mask], squares


def load_normalized_velocity_error(config: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    metrics = pd.read_csv(FORWARD / "control_population_metrics.csv")
    metrics = metrics.loc[(metrics["control_kind"] == "median") & metrics["experiment"].str.fullmatch(r"SQ\d{2}")
                          & (metrics["population"] == "central_50km") & (metrics["support_stratum"] == "all")
                          & (metrics["configuration"] == config)].set_index("experiment")
    with np.load(FOOTPRINT_ERRORS / f"{config}_ten_square_footprint_errors.npz", allow_pickle=False) as z:
        chunks = []
        for number in range(1, 11):
            mask = (z["square_number"] == number) & z["central"].astype(bool)
            population_rms = float(metrics.loc[f"SQ{number:02d}", "observed_vector_rms_m_per_a"])
            chunks.append(np.column_stack([z["x"][mask] / 1000.0, z["y"][mask] / 1000.0,
                                           100.0 * z["error_magnitude"][mask] / population_rms]))
    values = np.concatenate(chunks)
    return values[:, 0], values[:, 1], values[:, 2]


def draw_figure7_row(axes: np.ndarray, config: str, dmax: float, add_locator: bool) -> tuple[object, object]:
    coords, _, _, diff, squares = load_c_fields(config)
    vx, vy, verr = load_normalized_velocity_error(config)
    r, v = region_context(), aggregate_velocity_grid()
    for ax in axes:
        draw_speed_basemap(ax, r, v, alpha=.27)
    cim = axes[0].scatter(coords[:, 0], coords[:, 1], c=diff, s=2.0, cmap="RdBu_r",
                          norm=TwoSlopeNorm(vcenter=0, vmin=-dmax, vmax=dmax), linewidths=0, rasterized=True, zorder=2)
    vim = axes[1].scatter(vx, vy, c=verr, s=.8, cmap="inferno", norm=LogNorm(vmin=1, vmax=500),
                          linewidths=0, rasterized=True, zorder=2)
    axes[0].set_title(r"Median predicted $C$ minus inversion-reference $C$")
    axes[1].set_title("Local vector error / population RMS observed speed")
    for ax in axes:
        for row in squares.itertuples():
            ax.add_patch(Rectangle((row.test_xmin_m/1000, row.test_ymin_m/1000), 50, 50,
                                   fill=False, edgecolor="0.15", lw=.65, zorder=3))
        map_axes(ax, r["outline"])
    for ax in axes:
        add_antarctica_locator(ax, r["outline"])
    return cim, vim


def c_velocity_subfigure(config: str, dmax: float) -> list[Path]:
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 4.25), constrained_layout=True)
    cim, vim = draw_figure7_row(axes, config, dmax, config == "CFG02")
    cb0 = fig.colorbar(cim, ax=axes[0], shrink=.76, pad=.02); cb0.set_label(r"$\Delta C$")
    cb1 = fig.colorbar(vim, ax=axes[1], shrink=.76, pad=.02, extend="max")
    cb1.set_label("Normalized local vector error (%)")
    fig.suptitle(f"{CONFIG_LABELS[config]} ({config})", y=1.01, fontsize=10.5)
    return save(fig, f"figure7_{config.lower()}_c_velocity_comparison")


def c_velocity_single_panel(config: str, kind: str, dmax: float) -> list[Path]:
    r, v = region_context(), aggregate_velocity_grid()
    squares = square_table()
    fig, ax = plt.subplots(figsize=(4.6, 4.45), constrained_layout=True)
    draw_speed_basemap(ax, r, v, alpha=.27)
    if kind == "c_difference":
        coords, _, _, diff, _ = load_c_fields(config)
        image = ax.scatter(coords[:, 0], coords[:, 1], c=diff, s=2.0, cmap="RdBu_r",
                           norm=TwoSlopeNorm(vcenter=0, vmin=-dmax, vmax=dmax),
                           linewidths=0, rasterized=True, zorder=2)
        colorbar = fig.colorbar(image, ax=ax, shrink=.88, pad=.02)
        colorbar.set_label(r"$\Delta C$")
        suffix = "c_difference"
    elif kind == "velocity_error":
        vx, vy, verr = load_normalized_velocity_error(config)
        image = ax.scatter(vx, vy, c=verr, s=.8, cmap="inferno",
                           norm=LogNorm(vmin=1, vmax=500), linewidths=0,
                           rasterized=True, zorder=2)
        colorbar = fig.colorbar(image, ax=ax, shrink=.88, pad=.02, extend="max")
        colorbar.set_label("Normalized local vector error (%)")
        suffix = "velocity_error"
    else:
        raise ValueError(f"Unknown Figure 7 panel kind: {kind}")
    for row in squares.itertuples():
        ax.add_patch(Rectangle((row.test_xmin_m/1000, row.test_ymin_m/1000), 50, 50,
                               fill=False, edgecolor="0.15", lw=.65, zorder=3))
    map_axes(ax, r["outline"])
    add_antarctica_locator(ax, r["outline"])
    return save(fig, f"figure7_{config.lower()}_{suffix}")


def figure7() -> list[Path]:
    all_diff = []
    for cfg in ("CFG02", "CFG01"):
        _, _, _, diff, _ = load_c_fields(cfg)
        all_diff.append(diff)
    dmax = float(np.quantile(np.abs(np.concatenate(all_diff)), .995))
    paths = []
    paths.extend(c_velocity_subfigure("CFG02", dmax))
    paths.extend(c_velocity_subfigure("CFG01", dmax))
    for config in ("CFG02", "CFG01"):
        paths.extend(c_velocity_single_panel(config, "c_difference", dmax))
        paths.extend(c_velocity_single_panel(config, "velocity_error", dmax))
    combined, axes = plt.subplots(2, 2, figsize=(8.2, 7.6), constrained_layout=True, sharex=True, sharey=True)
    images = []
    for row, config in enumerate(("CFG02", "CFG01")):
        images.append(draw_figure7_row(axes[row], config, dmax, row == 0))
        axes[row, 0].text(.99, .02, f"{config}: {CONFIG_LABELS[config]}", transform=axes[row, 0].transAxes,
                          ha="right", va="bottom", fontsize=7.2,
                          bbox=dict(facecolor="white", edgecolor="0.4", alpha=.9, pad=2))
    cb0 = combined.colorbar(images[0][0], ax=axes[:, 0], shrink=.78, pad=.02); cb0.set_label(r"$\Delta C$")
    cb1 = combined.colorbar(images[0][1], ax=axes[:, 1], shrink=.78, pad=.02, extend="max")
    cb1.set_label("Normalized local vector error (%)")
    paths.extend(save(combined, "figure7_c_velocity_comparison_preview"))
    return paths


def figure8() -> list[Path]:
    support = support_rows()
    perf = pd.read_csv(FORWARD / "control_population_metrics.csv")
    perf = perf.loc[(perf["control_kind"] == "median") & perf["experiment"].str.fullmatch(r"SQ\d{2}")
                    & (perf["population"] == "central_50km") & (perf["support_stratum"] == "all")]
    cmet = pd.read_csv(C_DIAG / "control_population_c_metrics.csv")
    cmet = cmet.loc[(cmet["control_kind"] == "median") & cmet["experiment"].str.fullmatch(r"SQ\d{2}")
                    & (cmet["population"] == "central_50km")]
    df = support.merge(perf[["experiment", "configuration", "vector_rmse_m_per_a"]],
                       on=["experiment", "configuration"], validate="one_to_one")
    df = df.merge(cmet[["experiment", "configuration", "C_rmse"]], on=["experiment", "configuration"], validate="one_to_one")
    fig, axes = plt.subplots(1, 2, figsize=(10.8, 4.4), constrained_layout=True, sharey=True)
    xcols = [("joint_coverage", "Joint input support (%)"), ("C_rmse", "RMSE relative to inversion $C$")]
    for ax, (xcol, xlabel) in zip(axes, xcols):
        for square, group in df.groupby("experiment"):
            group = group.sort_values(xcol)
            x = 100*group[xcol] if xcol == "joint_coverage" else group[xcol]
            ax.plot(x, group["vector_rmse_m_per_a"], color="0.82", lw=.6, zorder=1)
        for cfg in CONFIGS:
            group = df.loc[df["configuration"] == cfg]
            x = 100*group[xcol] if xcol == "joint_coverage" else group[xcol]
            ax.scatter(x, group["vector_rmse_m_per_a"], s=28, color=CONFIG_COLORS[cfg], edgecolor="white", lw=.35,
                       label=f"{cfg} {CONFIG_LABELS[cfg]}", zorder=2)
        ax.set_xlabel(xlabel); ax.grid(axis="y", color="0.9", lw=.5)
        ax.set_yscale("log")
    axes[0].set_ylabel("Held-out velocity vector RMSE (m a$^{-1}$)")
    axes[0].set_title("Input support does not determine physical skill")
    axes[1].set_title("Closer agreement in $C$ generally tracks velocity skill")
    handles, labels = axes[1].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", bbox_to_anchor=(.5, -.06), ncol=3, frameon=False)
    return save(fig, "figure8_support_and_c_diagnostics")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    style()
    outputs: list[Path] = []
    outputs += generate_tables()
    outputs += figure1()
    outputs += figure3()
    outputs += figure4()
    outputs += figure7()
    manifest = {
        "schema": "jog-revision-prewriting-figure-bundle-v1",
        "status": "complete",
        "scope": "Tables 1-3 and retained working Figures 1,3,4,7; Figures 5-6 are generated separately; working Figures 2 and 8 are retired",
        "retired_outputs": {
            "figure2_workflow": "Retired from the active manuscript plan because the workflow is adequately described in prose and methods.",
            "figure8_support_and_c_diagnostics": "Retired because its useful relationships are reported directly in Figure 4, Figure 7, and the accompanying text."
        },
        "active_reporting_metrics": [
            "vector_velocity_RMSE_m_per_a",
            "RMSE_ML_over_RMSE_uniform_C",
            "simultaneous_marginal_and_joint_support_fraction"
        ],
        "archived_not_reported_metric": "P_exp",
        "panel_letters_in_artwork": False,
        "outputs": {p.name: sha(p) for p in outputs},
        "inputs": {
            "selected_squares": sha(DESIGN / "selected_squares.csv"),
            "support_categories": sha(SUPPORT / "support_categories.csv"),
            "forward_metrics": sha(FORWARD / "control_population_metrics.csv"),
            "c_metrics": sha(C_DIAG / "control_population_c_metrics.csv"),
            "square_summary": sha(REPORTING / "square_equal_weight_summary.csv"),
            "observed_speed_basemap": sha(OUT / "revision_velocity_grid_5km.npz"),
            "antarctica_land": sha(ANTARCTICA_LAND),
            "footprint_error_export": sha(FOOTPRINT_ERRORS / "footprint_error_export_manifest.json"),
        },
    }
    body = json.dumps(manifest, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    manifest["manifest_id"] = "sha256-json-v1-" + hashlib.sha256(body).hexdigest()
    (OUT / "prewriting_figure_bundle_manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True)+"\n")
    print(json.dumps({"status": "complete", "outputs": len(outputs), "manifest_id": manifest["manifest_id"]}, indent=2))


if __name__ == "__main__":
    main()
